/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarCertificadoRouteImport } from './routes/verificar-certificado'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppReceitasRouteImport } from './routes/app.receitas'
import { Route as AppProgressoRouteImport } from './routes/app.progresso'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppMateriaisRouteImport } from './routes/app.materiais'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppCursosRouteImport } from './routes/app.cursos'
import { Route as AppCertificadosRouteImport } from './routes/app.certificados'
import { Route as AppAoVivoRouteImport } from './routes/app.ao-vivo'
import { Route as AppAfiliadosRouteImport } from './routes/app.afiliados'
import { Route as ApiMaterialDownloadRouteImport } from './routes/api.material-download'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminStatusRouteImport } from './routes/admin.status'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminReconciliacaoRouteImport } from './routes/admin.reconciliacao'
import { Route as AdminReceitasRouteImport } from './routes/admin.receitas'
import { Route as AdminRankingRouteImport } from './routes/admin.ranking'
import { Route as AdminNotificacoesRouteImport } from './routes/admin.notificacoes'
import { Route as AdminMateriaisRouteImport } from './routes/admin.materiais'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminFeedbacksRouteImport } from './routes/admin.feedbacks'
import { Route as AdminEbooksRouteImport } from './routes/admin.ebooks'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminChatbotRouteImport } from './routes/admin.chatbot'
import { Route as AdminAoVivoRouteImport } from './routes/admin.ao-vivo'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAfiliadosRouteImport } from './routes/admin.afiliados'
import { Route as AppCursosIndexRouteImport } from './routes/app.cursos.index'
import { Route as AppAfiliadosIndexRouteImport } from './routes/app.afiliados.index'
import { Route as AppEbooksEbookIdRouteImport } from './routes/app.ebooks.$ebookId'
import { Route as AppCursosPreviewRouteImport } from './routes/app.cursos.preview'
import { Route as AppCursosCourseIdRouteImport } from './routes/app.cursos.$courseId'
import { Route as AppAfiliadosRedeRouteImport } from './routes/app.afiliados.rede'
import { Route as AppAfiliadosMateriaisRouteImport } from './routes/app.afiliados.materiais'
import { Route as AppAfiliadosLinksRouteImport } from './routes/app.afiliados.links'
import { Route as AppAfiliadosFinanceiroRouteImport } from './routes/app.afiliados.financeiro'
import { Route as AppAfiliadosConfigRouteImport } from './routes/app.afiliados.config'
import { Route as ApiPublicOpsRecoveryRouteImport } from './routes/api/public/ops-recovery'
import { Route as ApiPublicDriveVideoRouteImport } from './routes/api/public/drive-video'
import { Route as ApiPublicDailyUpdatesReportRouteImport } from './routes/api/public/daily-updates-report'
import { Route as ApiPublicDailyFinancialReportRouteImport } from './routes/api/public/daily-financial-report'
import { Route as AdminRankingCampanhasRouteImport } from './routes/admin.ranking.campanhas'
import { Route as AdminAlunosStudentIdRouteImport } from './routes/admin.alunos.$studentId'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'
import { Route as ApiPublicManifestWebmanifestRouteImport } from './routes/api/public/manifest.webmanifest'

const VerificarCertificadoRoute = VerificarCertificadoRouteImport.update({
  id: '/verificar-certificado',
  path: '/verificar-certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressoRoute = AppProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMateriaisRoute = AppMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificadosRoute = AppCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => AppRoute,
} as any)
const AppAoVivoRoute = AppAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const ApiMaterialDownloadRoute = ApiMaterialDownloadRouteImport.update({
  id: '/api/material-download',
  path: '/api/material-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatusRoute = AdminStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliacaoRoute = AdminReconciliacaoRouteImport.update({
  id: '/reconciliacao',
  path: '/reconciliacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitasRoute = AdminReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingRoute = AdminRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriaisRoute = AdminMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbacksRoute = AdminFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEbooksRoute = AdminEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAoVivoRoute = AdminAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const AppCursosIndexRoute = AppCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAfiliadosIndexRoute = AppAfiliadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppEbooksEbookIdRoute = AppEbooksEbookIdRouteImport.update({
  id: '/ebooks/$ebookId',
  path: '/ebooks/$ebookId',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosPreviewRoute = AppCursosPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppCursosCourseIdRoute = AppCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCursosRoute,
} as any)
const AppAfiliadosRedeRoute = AppAfiliadosRedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosMateriaisRoute = AppAfiliadosMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosLinksRoute = AppAfiliadosLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosFinanceiroRoute = AppAfiliadosFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const AppAfiliadosConfigRoute = AppAfiliadosConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppAfiliadosRoute,
} as any)
const ApiPublicOpsRecoveryRoute = ApiPublicOpsRecoveryRouteImport.update({
  id: '/api/public/ops-recovery',
  path: '/api/public/ops-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveVideoRoute = ApiPublicDriveVideoRouteImport.update({
  id: '/api/public/drive-video',
  path: '/api/public/drive-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyUpdatesReportRoute =
  ApiPublicDailyUpdatesReportRouteImport.update({
    id: '/api/public/daily-updates-report',
    path: '/api/public/daily-updates-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDailyFinancialReportRoute =
  ApiPublicDailyFinancialReportRouteImport.update({
    id: '/api/public/daily-financial-report',
    path: '/api/public/daily-financial-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRankingCampanhasRoute = AdminRankingCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRankingRoute,
} as any)
const AdminAlunosStudentIdRoute = AdminAlunosStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AdminAlunosRoute,
} as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestWebmanifestRoute =
  ApiPublicManifestWebmanifestRouteImport.update({
    id: '/api/public/manifest/webmanifest',
    path: '/api/public/manifest/webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/ranking': typeof AdminRankingRouteWithChildren
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/reconciliacao': typeof AdminReconciliacaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/material-download': typeof ApiMaterialDownloadRoute
  '/app/afiliados': typeof AppAfiliadosRouteWithChildren
  '/app/ao-vivo': typeof AppAoVivoRoute
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/admin/ranking/campanhas': typeof AdminRankingCampanhasRoute
  '/api/public/daily-financial-report': typeof ApiPublicDailyFinancialReportRoute
  '/api/public/daily-updates-report': typeof ApiPublicDailyUpdatesReportRoute
  '/api/public/drive-video': typeof ApiPublicDriveVideoRoute
  '/api/public/ops-recovery': typeof ApiPublicOpsRecoveryRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/afiliados/materiais': typeof AppAfiliadosMateriaisRoute
  '/app/afiliados/rede': typeof AppAfiliadosRedeRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/afiliados/': typeof AppAfiliadosIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/ranking': typeof AdminRankingRouteWithChildren
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/reconciliacao': typeof AdminReconciliacaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/material-download': typeof ApiMaterialDownloadRoute
  '/app/ao-vivo': typeof AppAoVivoRoute
  '/app/certificados': typeof AppCertificadosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/admin/ranking/campanhas': typeof AdminRankingCampanhasRoute
  '/api/public/daily-financial-report': typeof ApiPublicDailyFinancialReportRoute
  '/api/public/daily-updates-report': typeof ApiPublicDailyUpdatesReportRoute
  '/api/public/drive-video': typeof ApiPublicDriveVideoRoute
  '/api/public/ops-recovery': typeof ApiPublicOpsRecoveryRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/afiliados/materiais': typeof AppAfiliadosMateriaisRoute
  '/app/afiliados/rede': typeof AppAfiliadosRedeRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/afiliados': typeof AppAfiliadosIndexRoute
  '/app/cursos': typeof AppCursosIndexRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/inicio': typeof InicioRoute
  '/login': typeof LoginRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alunos': typeof AdminAlunosRouteWithChildren
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/ranking': typeof AdminRankingRouteWithChildren
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/reconciliacao': typeof AdminReconciliacaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/material-download': typeof ApiMaterialDownloadRoute
  '/app/afiliados': typeof AppAfiliadosRouteWithChildren
  '/app/ao-vivo': typeof AppAoVivoRoute
  '/app/certificados': typeof AppCertificadosRoute
  '/app/cursos': typeof AppCursosRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/materiais': typeof AppMateriaisRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/progresso': typeof AppProgressoRoute
  '/app/receitas': typeof AppReceitasRoute
  '/app/suporte': typeof AppSuporteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/alunos/$studentId': typeof AdminAlunosStudentIdRoute
  '/admin/ranking/campanhas': typeof AdminRankingCampanhasRoute
  '/api/public/daily-financial-report': typeof ApiPublicDailyFinancialReportRoute
  '/api/public/daily-updates-report': typeof ApiPublicDailyUpdatesReportRoute
  '/api/public/drive-video': typeof ApiPublicDriveVideoRoute
  '/api/public/ops-recovery': typeof ApiPublicOpsRecoveryRoute
  '/app/afiliados/config': typeof AppAfiliadosConfigRoute
  '/app/afiliados/financeiro': typeof AppAfiliadosFinanceiroRoute
  '/app/afiliados/links': typeof AppAfiliadosLinksRoute
  '/app/afiliados/materiais': typeof AppAfiliadosMateriaisRoute
  '/app/afiliados/rede': typeof AppAfiliadosRedeRoute
  '/app/cursos/$courseId': typeof AppCursosCourseIdRoute
  '/app/cursos/preview': typeof AppCursosPreviewRoute
  '/app/ebooks/$ebookId': typeof AppEbooksEbookIdRoute
  '/app/afiliados/': typeof AppAfiliadosIndexRoute
  '/app/cursos/': typeof AppCursosIndexRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/verificar-certificado'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/chatbot'
    | '/admin/cursos'
    | '/admin/downloads'
    | '/admin/ebooks'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/logs'
    | '/admin/materiais'
    | '/admin/notificacoes'
    | '/admin/ranking'
    | '/admin/receitas'
    | '/admin/reconciliacao'
    | '/admin/relatorios'
    | '/admin/status'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/api/material-download'
    | '/app/afiliados'
    | '/app/ao-vivo'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/financeiro'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/auth/callback'
    | '/admin/'
    | '/app/'
    | '/admin/alunos/$studentId'
    | '/admin/ranking/campanhas'
    | '/api/public/daily-financial-report'
    | '/api/public/daily-updates-report'
    | '/api/public/drive-video'
    | '/api/public/ops-recovery'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/afiliados/materiais'
    | '/app/afiliados/rede'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/afiliados/'
    | '/app/cursos/'
    | '/api/public/manifest/webmanifest'
    | '/api/public/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/verificar-certificado'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/chatbot'
    | '/admin/cursos'
    | '/admin/downloads'
    | '/admin/ebooks'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/logs'
    | '/admin/materiais'
    | '/admin/notificacoes'
    | '/admin/ranking'
    | '/admin/receitas'
    | '/admin/reconciliacao'
    | '/admin/relatorios'
    | '/admin/status'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/api/material-download'
    | '/app/ao-vivo'
    | '/app/certificados'
    | '/app/financeiro'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/auth/callback'
    | '/admin'
    | '/app'
    | '/admin/alunos/$studentId'
    | '/admin/ranking/campanhas'
    | '/api/public/daily-financial-report'
    | '/api/public/daily-updates-report'
    | '/api/public/drive-video'
    | '/api/public/ops-recovery'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/afiliados/materiais'
    | '/app/afiliados/rede'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/afiliados'
    | '/app/cursos'
    | '/api/public/manifest/webmanifest'
    | '/api/public/webhooks/asaas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/inicio'
    | '/login'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/verificar-certificado'
    | '/admin/afiliados'
    | '/admin/alunos'
    | '/admin/ao-vivo'
    | '/admin/chatbot'
    | '/admin/cursos'
    | '/admin/downloads'
    | '/admin/ebooks'
    | '/admin/feedbacks'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/logs'
    | '/admin/materiais'
    | '/admin/notificacoes'
    | '/admin/ranking'
    | '/admin/receitas'
    | '/admin/reconciliacao'
    | '/admin/relatorios'
    | '/admin/status'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/api/material-download'
    | '/app/afiliados'
    | '/app/ao-vivo'
    | '/app/certificados'
    | '/app/cursos'
    | '/app/financeiro'
    | '/app/materiais'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/progresso'
    | '/app/receitas'
    | '/app/suporte'
    | '/auth/callback'
    | '/admin/'
    | '/app/'
    | '/admin/alunos/$studentId'
    | '/admin/ranking/campanhas'
    | '/api/public/daily-financial-report'
    | '/api/public/daily-updates-report'
    | '/api/public/drive-video'
    | '/api/public/ops-recovery'
    | '/app/afiliados/config'
    | '/app/afiliados/financeiro'
    | '/app/afiliados/links'
    | '/app/afiliados/materiais'
    | '/app/afiliados/rede'
    | '/app/cursos/$courseId'
    | '/app/cursos/preview'
    | '/app/ebooks/$ebookId'
    | '/app/afiliados/'
    | '/app/cursos/'
    | '/api/public/manifest/webmanifest'
    | '/api/public/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  InicioRoute: typeof InicioRoute
  LoginRoute: typeof LoginRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  VerificarCertificadoRoute: typeof VerificarCertificadoRoute
  ApiMaterialDownloadRoute: typeof ApiMaterialDownloadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicDailyFinancialReportRoute: typeof ApiPublicDailyFinancialReportRoute
  ApiPublicDailyUpdatesReportRoute: typeof ApiPublicDailyUpdatesReportRoute
  ApiPublicDriveVideoRoute: typeof ApiPublicDriveVideoRoute
  ApiPublicOpsRecoveryRoute: typeof ApiPublicOpsRecoveryRoute
  ApiPublicManifestWebmanifestRoute: typeof ApiPublicManifestWebmanifestRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-certificado': {
      id: '/verificar-certificado'
      path: '/verificar-certificado'
      fullPath: '/verificar-certificado'
      preLoaderRoute: typeof VerificarCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receitas': {
      id: '/app/receitas'
      path: '/receitas'
      fullPath: '/app/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progresso': {
      id: '/app/progresso'
      path: '/progresso'
      fullPath: '/app/progresso'
      preLoaderRoute: typeof AppProgressoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materiais': {
      id: '/app/materiais'
      path: '/materiais'
      fullPath: '/app/materiais'
      preLoaderRoute: typeof AppMateriaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos': {
      id: '/app/cursos'
      path: '/cursos'
      fullPath: '/app/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificados': {
      id: '/app/certificados'
      path: '/certificados'
      fullPath: '/app/certificados'
      preLoaderRoute: typeof AppCertificadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ao-vivo': {
      id: '/app/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/app/ao-vivo'
      preLoaderRoute: typeof AppAoVivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/afiliados': {
      id: '/app/afiliados'
      path: '/afiliados'
      fullPath: '/app/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/material-download': {
      id: '/api/material-download'
      path: '/api/material-download'
      fullPath: '/api/material-download'
      preLoaderRoute: typeof ApiMaterialDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/status': {
      id: '/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AdminStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliacao': {
      id: '/admin/reconciliacao'
      path: '/reconciliacao'
      fullPath: '/admin/reconciliacao'
      preLoaderRoute: typeof AdminReconciliacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receitas': {
      id: '/admin/receitas'
      path: '/receitas'
      fullPath: '/admin/receitas'
      preLoaderRoute: typeof AdminReceitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ranking': {
      id: '/admin/ranking'
      path: '/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AdminRankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materiais': {
      id: '/admin/materiais'
      path: '/materiais'
      fullPath: '/admin/materiais'
      preLoaderRoute: typeof AdminMateriaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedbacks': {
      id: '/admin/feedbacks'
      path: '/feedbacks'
      fullPath: '/admin/feedbacks'
      preLoaderRoute: typeof AdminFeedbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ebooks': {
      id: '/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AdminEbooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ao-vivo': {
      id: '/admin/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/admin/ao-vivo'
      preLoaderRoute: typeof AdminAoVivoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/cursos/': {
      id: '/app/cursos/'
      path: '/'
      fullPath: '/app/cursos/'
      preLoaderRoute: typeof AppCursosIndexRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/afiliados/': {
      id: '/app/afiliados/'
      path: '/'
      fullPath: '/app/afiliados/'
      preLoaderRoute: typeof AppAfiliadosIndexRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/ebooks/$ebookId': {
      id: '/app/ebooks/$ebookId'
      path: '/ebooks/$ebookId'
      fullPath: '/app/ebooks/$ebookId'
      preLoaderRoute: typeof AppEbooksEbookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cursos/preview': {
      id: '/app/cursos/preview'
      path: '/preview'
      fullPath: '/app/cursos/preview'
      preLoaderRoute: typeof AppCursosPreviewRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/cursos/$courseId': {
      id: '/app/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/app/cursos/$courseId'
      preLoaderRoute: typeof AppCursosCourseIdRouteImport
      parentRoute: typeof AppCursosRoute
    }
    '/app/afiliados/rede': {
      id: '/app/afiliados/rede'
      path: '/rede'
      fullPath: '/app/afiliados/rede'
      preLoaderRoute: typeof AppAfiliadosRedeRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/materiais': {
      id: '/app/afiliados/materiais'
      path: '/materiais'
      fullPath: '/app/afiliados/materiais'
      preLoaderRoute: typeof AppAfiliadosMateriaisRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/links': {
      id: '/app/afiliados/links'
      path: '/links'
      fullPath: '/app/afiliados/links'
      preLoaderRoute: typeof AppAfiliadosLinksRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/financeiro': {
      id: '/app/afiliados/financeiro'
      path: '/financeiro'
      fullPath: '/app/afiliados/financeiro'
      preLoaderRoute: typeof AppAfiliadosFinanceiroRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/app/afiliados/config': {
      id: '/app/afiliados/config'
      path: '/config'
      fullPath: '/app/afiliados/config'
      preLoaderRoute: typeof AppAfiliadosConfigRouteImport
      parentRoute: typeof AppAfiliadosRoute
    }
    '/api/public/ops-recovery': {
      id: '/api/public/ops-recovery'
      path: '/api/public/ops-recovery'
      fullPath: '/api/public/ops-recovery'
      preLoaderRoute: typeof ApiPublicOpsRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-video': {
      id: '/api/public/drive-video'
      path: '/api/public/drive-video'
      fullPath: '/api/public/drive-video'
      preLoaderRoute: typeof ApiPublicDriveVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-updates-report': {
      id: '/api/public/daily-updates-report'
      path: '/api/public/daily-updates-report'
      fullPath: '/api/public/daily-updates-report'
      preLoaderRoute: typeof ApiPublicDailyUpdatesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-financial-report': {
      id: '/api/public/daily-financial-report'
      path: '/api/public/daily-financial-report'
      fullPath: '/api/public/daily-financial-report'
      preLoaderRoute: typeof ApiPublicDailyFinancialReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ranking/campanhas': {
      id: '/admin/ranking/campanhas'
      path: '/campanhas'
      fullPath: '/admin/ranking/campanhas'
      preLoaderRoute: typeof AdminRankingCampanhasRouteImport
      parentRoute: typeof AdminRankingRoute
    }
    '/admin/alunos/$studentId': {
      id: '/admin/alunos/$studentId'
      path: '/$studentId'
      fullPath: '/admin/alunos/$studentId'
      preLoaderRoute: typeof AdminAlunosStudentIdRouteImport
      parentRoute: typeof AdminAlunosRoute
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/webmanifest': {
      id: '/api/public/manifest/webmanifest'
      path: '/api/public/manifest/webmanifest'
      fullPath: '/api/public/manifest/webmanifest'
      preLoaderRoute: typeof ApiPublicManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAlunosRouteChildren {
  AdminAlunosStudentIdRoute: typeof AdminAlunosStudentIdRoute
}

const AdminAlunosRouteChildren: AdminAlunosRouteChildren = {
  AdminAlunosStudentIdRoute: AdminAlunosStudentIdRoute,
}

const AdminAlunosRouteWithChildren = AdminAlunosRoute._addFileChildren(
  AdminAlunosRouteChildren,
)

interface AdminRankingRouteChildren {
  AdminRankingCampanhasRoute: typeof AdminRankingCampanhasRoute
}

const AdminRankingRouteChildren: AdminRankingRouteChildren = {
  AdminRankingCampanhasRoute: AdminRankingCampanhasRoute,
}

const AdminRankingRouteWithChildren = AdminRankingRoute._addFileChildren(
  AdminRankingRouteChildren,
)

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminAlunosRoute: typeof AdminAlunosRouteWithChildren
  AdminAoVivoRoute: typeof AdminAoVivoRoute
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminEbooksRoute: typeof AdminEbooksRoute
  AdminFeedbacksRoute: typeof AdminFeedbacksRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMateriaisRoute: typeof AdminMateriaisRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminRankingRoute: typeof AdminRankingRouteWithChildren
  AdminReceitasRoute: typeof AdminReceitasRoute
  AdminReconciliacaoRoute: typeof AdminReconciliacaoRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminStatusRoute: typeof AdminStatusRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminAlunosRoute: AdminAlunosRouteWithChildren,
  AdminAoVivoRoute: AdminAoVivoRoute,
  AdminChatbotRoute: AdminChatbotRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminEbooksRoute: AdminEbooksRoute,
  AdminFeedbacksRoute: AdminFeedbacksRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMateriaisRoute: AdminMateriaisRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminRankingRoute: AdminRankingRouteWithChildren,
  AdminReceitasRoute: AdminReceitasRoute,
  AdminReconciliacaoRoute: AdminReconciliacaoRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminStatusRoute: AdminStatusRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAfiliadosRouteChildren {
  AppAfiliadosConfigRoute: typeof AppAfiliadosConfigRoute
  AppAfiliadosFinanceiroRoute: typeof AppAfiliadosFinanceiroRoute
  AppAfiliadosLinksRoute: typeof AppAfiliadosLinksRoute
  AppAfiliadosMateriaisRoute: typeof AppAfiliadosMateriaisRoute
  AppAfiliadosRedeRoute: typeof AppAfiliadosRedeRoute
  AppAfiliadosIndexRoute: typeof AppAfiliadosIndexRoute
}

const AppAfiliadosRouteChildren: AppAfiliadosRouteChildren = {
  AppAfiliadosConfigRoute: AppAfiliadosConfigRoute,
  AppAfiliadosFinanceiroRoute: AppAfiliadosFinanceiroRoute,
  AppAfiliadosLinksRoute: AppAfiliadosLinksRoute,
  AppAfiliadosMateriaisRoute: AppAfiliadosMateriaisRoute,
  AppAfiliadosRedeRoute: AppAfiliadosRedeRoute,
  AppAfiliadosIndexRoute: AppAfiliadosIndexRoute,
}

const AppAfiliadosRouteWithChildren = AppAfiliadosRoute._addFileChildren(
  AppAfiliadosRouteChildren,
)

interface AppCursosRouteChildren {
  AppCursosCourseIdRoute: typeof AppCursosCourseIdRoute
  AppCursosPreviewRoute: typeof AppCursosPreviewRoute
  AppCursosIndexRoute: typeof AppCursosIndexRoute
}

const AppCursosRouteChildren: AppCursosRouteChildren = {
  AppCursosCourseIdRoute: AppCursosCourseIdRoute,
  AppCursosPreviewRoute: AppCursosPreviewRoute,
  AppCursosIndexRoute: AppCursosIndexRoute,
}

const AppCursosRouteWithChildren = AppCursosRoute._addFileChildren(
  AppCursosRouteChildren,
)

interface AppRouteChildren {
  AppAfiliadosRoute: typeof AppAfiliadosRouteWithChildren
  AppAoVivoRoute: typeof AppAoVivoRoute
  AppCertificadosRoute: typeof AppCertificadosRoute
  AppCursosRoute: typeof AppCursosRouteWithChildren
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMateriaisRoute: typeof AppMateriaisRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProgressoRoute: typeof AppProgressoRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEbooksEbookIdRoute: typeof AppEbooksEbookIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAfiliadosRoute: AppAfiliadosRouteWithChildren,
  AppAoVivoRoute: AppAoVivoRoute,
  AppCertificadosRoute: AppCertificadosRoute,
  AppCursosRoute: AppCursosRouteWithChildren,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMateriaisRoute: AppMateriaisRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProgressoRoute: AppProgressoRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
  AppEbooksEbookIdRoute: AppEbooksEbookIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  InicioRoute: InicioRoute,
  LoginRoute: LoginRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  VerificarCertificadoRoute: VerificarCertificadoRoute,
  ApiMaterialDownloadRoute: ApiMaterialDownloadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicDailyFinancialReportRoute: ApiPublicDailyFinancialReportRoute,
  ApiPublicDailyUpdatesReportRoute: ApiPublicDailyUpdatesReportRoute,
  ApiPublicDriveVideoRoute: ApiPublicDriveVideoRoute,
  ApiPublicOpsRecoveryRoute: ApiPublicOpsRecoveryRoute,
  ApiPublicManifestWebmanifestRoute: ApiPublicManifestWebmanifestRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
