ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'NEGOCIO DE ESPETINHOS';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'CURSO E CONTEUDO';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'PAGAMENTOS';