ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'CMV E PRECIFICACAO';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'EQUIPAMENTOS';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'CONSERVACAO E SEGURANCA ALIMENTAR';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'DELIVERY E VENDAS';
ALTER TYPE public.knowledge_category ADD VALUE IF NOT EXISTS 'GESTAO DO NEGOCIO';